[package]
name = "perseus"
version = "0.3.0-beta.13"
edition = "2018"
description = "A lightning-fast frontend web dev platform with full support for SSR and SSG."
authors = ["arctic_hen7 <arctic_hen7@pm.me>"]
license = "MIT"
repository = "https://github.com/arctic-hen7/perseus"
homepage = "https://arctic-hen7.github.io/perseus"
readme = "../../README.md"
keywords = ["wasm", "frontend", "webdev", "ssg", "ssr"]
categories = ["wasm", "web-programming", "development-tools", "asynchronous", "gui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sycamore = { version = "0.6", features = ["ssr"] }
sycamore-router = "0.6"
perseus-macro = { path = "../perseus-macro", version = "0.3.0-beta.13" }
# TODO review feature flags here
web-sys = { version = "0.3", features = ["Headers", "Navigator", "NodeList", "Request", "RequestInit", "RequestMode", "Response", "ReadableStream", "Window"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
fmterr = "0.1"
futures = "0.3"
urlencoding = "2.1"
chrono = "0.4"
http = "0.2"
async-trait = "0.1"
cfg-if = "1"
fluent-bundle = { version = "0.15", optional = true }
unic-langid = { version = "0.9", optional = true }

[features]
default = []
translator-fluent = ["fluent-bundle", "unic-langid"]
# This feature makes tinker-only plugins be registered (this flag is enabled internally in the engine)
tinker-plugins = []
# This feature enables server-side-only features, which should be used on both the server and in the builder
# This prevents leakage of server-side code
server-side = []
