[package]
name = "perseus"
version = "0.1.4"
edition = "2018"
description = "A lightning-fast frontend web dev platform with full support for SSR and SSG."
authors = ["arctic_hen7 <arctic_hen7@pm.me>"]
license = "MIT"
repository = "https://github.com/arctic-hen7/perseus"
homepage = "https://arctic-hen7.github.io/perseus"
readme = "../../README.md"
keywords = ["wasm", "frontend", "webdev", "ssg", "ssr"]
categories = ["wasm", "web-programming", "development-tools", "asynchronous", "gui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sycamore = { version = "0.6", features = ["ssr"] }
sycamore-router = "0.6"
web-sys = { version = "0.3", features = ["Headers", "Navigator", "Request", "RequestInit", "RequestMode", "Response", "ReadableStream", "Window"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
typetag = "0.1"
error-chain = "0.12"
futures = "0.3"
console_error_panic_hook = "0.1.6"
urlencoding = "2.1"
chrono = "0.4"
http = "0.2"
async-trait = "0.1"
fluent-bundle = { version = "0.15", optional = true }
unic-langid = { version = "0.9", optional = true }

[features]
default = ["translator-fluent", "translator-dflt-fluent"]
# Each `translator-dflt-*` feature enables a certain translator as the default, and is mutually exclusive with others like it
# One MUST be specified, or the crate will not compile
translator-fluent = ["fluent-bundle", "unic-langid"]
translator-dflt-fluent = ["translator-fluent", "fluent-bundle", "unic-langid"]
