[package]
name = "perseus-actix-web"
version = "0.4.0-beta.1"
edition = "2021"
description = "An integration that makes the Perseus frontend framework easy to use with Actix Web."
authors = ["arctic_hen7 <arctic_hen7@pm.me>"]
license = "MIT"
repository = "https://github.com/arctic-hen7/perseus"
homepage = "https://arctic-hen7.github.io/perseus"
readme = "./README.md"
keywords = ["wasm", "frontend", "webdev", "ssg", "ssr"]
categories = ["wasm", "web-programming::http-server", "development-tools", "asynchronous", "gui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
perseus = { path = "../perseus", version = "0.4.0-beta.1" }
actix-web = "=4.0.0-rc.3"
actix-http = "=3.0.0-rc.2" # Without this, Actix can introduce breaking changes in a dependency tree
# actix-router = "=0.5.0-rc.3"
actix-files = "=0.6.0-beta.16"
urlencoding = "2.1"
serde = "1"
serde_json = "1"
thiserror = "1"
fmterr = "0.1"
futures = "0.3"
sycamore = { version = "=0.8.0-beta.6", features = ["ssr"] }
