[package]
name = "perseus-example-fetching"
version = "0.4.0-beta.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
perseus = { path = "../../../packages/perseus", features = [ "hydrate" ] }
sycamore = "=0.8.0-beta.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwasm = "0.4"

# This makes sure `reqwest` is only included on the server-side (it won't compile at all for the browser)
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest = "0.11"
