[package]
name = "perseus-macro"
version = "0.2.0"
edition = "2018"
autotests = false

[lib]
proc-macro = true

# [[test]]
# name = "tests"
# path = "tests/progress.rs"

[dependencies]
quote = "1"
syn = "1"
proc-macro2 = "1"
darling = "0.13"
serde_json = "1"

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }
