# This file is temporary until the CLI is ready!

version="0.3.2"

[scripts]
build = [
    "cargo run",
    "wasm-pack build --target web",
    "rm -rf dist/pkg",
    "mv pkg/ dist/",
    "rollup main.js --format iife --file dist/pkg/bundle.js"
]
serve = [
    "cd server",
    "cargo run"
]
