name: Test

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cargo install bonnie
            - run: apt install firefox gecko-driver
            - name: Run Firefox WebDriver
              run: geckodriver &
            - name: Test Library
              run: bonnie ci
