name: Test

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cargo install bonnie
            - run: bonnie copy-subcrates
            - name: Run checks
              run: bonnie check
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cargo install bonnie
            - run: bonnie copy-subcrates
            - name: Run traditional tests
              run: cargo test --all
    # We now have a separate job for each example's E2E testing because they all take a while, we may as well run them in parallel
    e2e-test-example-basic:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cargo install bonnie
            - run: cargo install wasm-pack
            - run: sudo apt install firefox firefox-geckodriver
            - name: Run Firefox WebDriver
              run: geckodriver &
            - run: bonnie copy-subcrates
            - run: bonnie ci-prep
            - name: Run E2E tests
              run: bonnie test example basic --headless
    e2e-test-example-i18n:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cargo install bonnie
            - run: cargo install wasm-pack
            - run: sudo apt install firefox firefox-geckodriver
            - name: Run Firefox WebDriver
              run: geckodriver &
            - run: bonnie copy-subcrates
            - run: bonnie ci-prep
            - name: Run E2E tests
              run: bonnie test example i18n --headless
    # This one is liable to fail for no particular reason (`geckodriver` seems to get tired...)
    # It should be re-run if it fails unexpectedly, especially if the error message is something to do with WebDriver sessions
    e2e-test-example-showcase:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cargo install bonnie
            - run: cargo install wasm-pack
            - run: sudo apt install firefox firefox-geckodriver
            - name: Run Firefox WebDriver
              run: geckodriver &
            - run: bonnie copy-subcrates
            - run: bonnie ci-prep
            - name: Run E2E tests
              run: bonnie test example showcase --headless
